add guidelines for writing graphql queries/mutations
innovatrics/innovatrics-javascript pull request #16
Opened 2019-08-12 09:21 UTC by Paulooze

Update guideline with rules for writing GraphQL queries in ApolloClient, mainly for cache normalisation.

2019-08-12 11:38 UTC, soson approved these changes

2019-08-12 12:04 UTC, dhlavaty requested changes

2019-08-12 12:04 UTC, dhlavaty commented on README.md
> +
Pls add a simple explanation, why we should add `@connection` and an example implementation of `cache delete`

2019-08-13 10:13 UTC, dhlavaty approved these changes

2019-08-13 10:30 UTC, merged