update eslint depdendencies to latest
innovatrics/innovatrics-javascript pull request #25
Opened 2020-07-14 12:33 UTC by Paulooze

Updated eslint in every package - had to make some breaking changes in `typescript-eslint` config: 
  - https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-comment.md
  - https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md

2020-07-15 11:02 UTC, dhlavaty requested changes

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript-base/index.js
> +    "@typescript-eslint/explicit-module-boundary-types": "off",
pls explain in comment

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript-base/index.js
> +    "@typescript-eslint/naming-convention": [
probably should be ABOVE "the line"

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript-base/index.js
> +    "@typescript-eslint/ban-ts-comment": 2,
pls explain in comment

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript/index.js
> +    "@typescript-eslint/explicit-module-boundary-types": "off",
pls explain in comment

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript/index.js
> +    "@typescript-eslint/naming-convention": [
probably should be above "the line"

2020-07-15 11:02 UTC, dhlavaty commented on eslint-config-innovatrics-typescript/index.js
> +    "@typescript-eslint/ban-ts-comment": 2,
pls explain in comment

2020-07-15 12:44 UTC, gabor requested changes

2020-07-15 12:44 UTC, gabor commented on eslint-config-innovatrics-typescript-base/index.js
> +    "no-else-return": "off",
please add "// Gabor does not like this one" before the no-else-return :-]

2020-07-15 12:49 UTC, gabor approved these changes

2020-07-15 13:33 UTC, dhlavaty requested changes

2020-07-15 13:33 UTC, dhlavaty commented on eslint-config-innovatrics/index.js
>      "react/no-unused-prop-types": "off",
explain in comment pls

2020-07-15 13:33 UTC, dhlavaty commented on eslint-config-innovatrics/index.js
> +    "react/require-default-props": "off",
explain in comment pls

2020-07-16 05:43 UTC, dhlavaty approved these changes

2020-07-16 05:44 UTC, merged